/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#0b0d0d",
        "surface-container-low": "#191c1c",
        "surface-container": "#1d2020",
        "surface-container-high": "#232727",
        "surface-container-highest": "#333535",
        "surface": "#111414",
        "surface-dim": "#111414",
        "surface-bright": "#373a3a",
        "surface-variant": "#3f4848",
        "surface-tint": "#94d1d1",
        "background": "#111414",
        "on-background": "#e1e3e2",
        "on-surface": "#e1e3e2",
        "on-surface-variant": "#bfc8c8",
        "primary": "#94d1d1",
        "primary-container": "#004d4d",
        "primary-fixed": "#b1ecec",
        "primary-fixed-dim": "#94d1d1",
        "on-primary": "#003737",
        "on-primary-container": "#b1ecec",
        "on-primary-fixed": "#002020",
        "on-primary-fixed-variant": "#004f4f",
        "secondary": "#bfc8c8",
        "secondary-container": "#3f4848",
        "secondary-fixed": "#dbe4e4",
        "secondary-fixed-dim": "#bfc8c8",
        "on-secondary": "#2d3131",
        "on-secondary-fixed": "#111414",
        "on-secondary-container": "#adb7b7",
        "on-secondary-fixed-variant": "#3f4848",
        "tertiary": "#94d1d1",
        "tertiary-container": "#004d4d",
        "tertiary-fixed": "#94d1d1",
        "tertiary-fixed-dim": "#7abdbd",
        "on-tertiary": "#003737",
        "on-tertiary-container": "#002020",
        "on-tertiary-fixed": "#002020",
        "on-tertiary-fixed-variant": "#004f4f",
        "outline": "#899292",
        "outline-variant": "#3f4848",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e1e3e2",
        "inverse-on-surface": "#2d3131",
        "inverse-primary": "#006a6a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Exo 2", "sans-serif"],
        body: ["Exo 2", "sans-serif"],
        label: ["Exo 2", "sans-serif"],
      },
    },
  },
  plugins: [],
};
